version: "3"
services:

  elasticsearch:
    image: elastic/elasticsearch:$ELASTIC_VERSION
    container_name: elasticsearch
    restart: unless-stopped
    cpus: 2
    mem_limit: 2048m
    mem_reservation: 1024m
    networks:
      - dockernet
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=$ELASTIC_SECURITY
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: curl -u elastic:changeme --silent --fail localhost:9200/_cat/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
    labels:
      co.elastic.logs/enabled: false

  kibana:
    image: elastic/kibana:$ELASTIC_VERSION
    container_name: kibana
    restart: unless-stopped
    cpus: 1
    mem_limit: 1024m
    mem_reservation: 512m
    networks:
      - dockernet
    ports:
      - 5601:5601
    secrets:
      - source: kibana.yml
        target: /usr/share/kibana/config/kibana.yml
    depends_on:
      elasticsearch:
        condition: service_healthy
    labels:
      co.elastic.logs/enabled: false

  apm-server:
    image: elastic/apm-server:$ELASTIC_VERSION
    container_name: apm-server
    restart: unless-stopped
    cpus: 0.1
    mem_limit: 512m
    mem_reservation: 256m
    networks:
      - dockernet
    ports:
      - 8200:8200
    user: root 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    secrets:
      - source: apm-server.yml
        target: /usr/share/apm-server/apm-server.yml
    command: -e --strict.perms=false
    depends_on:
      elasticsearch:
        condition: service_healthy
    labels:
      co.elastic.logs/enabled: false

  metricbeat:
    container_name: metricbeat
    user: root 
    image: elastic/metricbeat:$ELASTIC_VERSION
    restart: unless-stopped
    cpus: 0.1
    mem_limit: 512m
    mem_reservation: 256m
    environment:
      - system.hostfs=/hostfs
    secrets:
      - source: metricbeat.yml
        target: /usr/share/metricbeat/metricbeat.yml
    volumes:
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
    command: -e --strict.perms=false
    networks:
      - dockernet
    depends_on:
      elasticsearch:
        condition: service_healthy
    labels:
      co.elastic.logs/enabled: false

  filebeat:
    container_name: filebeat
    image: elastic/filebeat:$ELASTIC_VERSION
    user: root 
    restart: unless-stopped
    cpus: 0.1
    mem_limit: 512m
    mem_reservation: 256m
    secrets:
      - source: filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -e --strict.perms=false
    networks:
      - dockernet
    depends_on:
      elasticsearch:
        condition: service_healthy
    labels:
      co.elastic.logs/enabled: false

  heartbeat:
    container_name: heartbeat
    image: elastic/heartbeat:$ELASTIC_VERSION
    user: root
    restart: unless-stopped
    cpus: 0.1
    mem_limit: 512m
    mem_reservation: 256m
    depends_on: 
      elasticsearch:
        condition: service_healthy
    command: -e --strict.perms=false
    secrets:
      - source: heartbeat.yml
        target: /usr/share/heartbeat/heartbeat.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - dockernet

    healthcheck:
      test: heartbeat --strict.perms=false test config
    labels:
      co.elastic.logs/enabled: false

networks:
  dockernet:
    external: true

secrets:
  apm-server.yml:
    file: ./config/apm-server.yml
  kibana.yml:
    file: ./config/kibana.yml
  metricbeat.yml:
    file: ./config/metricbeat.yml
  filebeat.yml:
    file: ./config/filebeat.yml
  heartbeat.yml:
    file: ./config/heartbeat.yml